#!/usr/bin/env sh
npm run import -- "./books/a-study-in-scarlet.htm" --bookOrder=1 --strategy "stud"
npm run import -- "./books/the-sign-of-the-four.htm" --bookOrder=2 --strategy "sign"
npm run import -- "./books/the-adventures-of-sherlock-holmes.htm" --bookOrder=3 --strategy "adve"
npm run import -- "./books/the-memoirs-of-sherlock-holmes.htm" --bookOrder=4 --strategy "memo"
npm run import -- "./books/the-hound-of-the-baskervilles.htm" --bookOrder=5 --strategy "houn"
npm run import -- "./books/the-return-of-sherlock-holmes.htm" --bookOrder=6 --strategy "retu"
npm run import -- "./books/his-last-bow.htm" --bookOrder=7 --strategy "last"
npm run import -- "./books/the-valley-of-fear.htm" --bookOrder=8 --strategy "fear"
